// action
export const ADD_TEAM='ADD_TEAM';
export const DELETE_TEAM='DELETE_TEAM';

// state
export const REQUEST_TEAM='REQUEST_TEAM';
export const RECEIVE_TEAM='RECEIVE_TEAM';
export const RECEIVE_TEAMS='RECEIVE_TEAMS';
export const RECEIVE_RESULT='RECEIVE_RESULT';

// users
export const REQUEST_LOGIN='REQUEST_LOGIN';
export const LOGED_IN='LOGED_IN';
export const NOT_LOGED_IN='NOT_LOGED_IN';
export const RECEIVE_LOGIN='RECEIVE_LOGIN';
export const OPEN_LOGIN_MODAL='OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL='CLOSE_LOGIN_MODAL';
export const OPEN_SIGNUP_MODAL='OPEN_SIGNUP_MODAL';
export const CLOSE_SIGNUP_MODAL='CLOSE_SIGNUP_MODAL';
export const OPEN_SIGNUP_FORM_MODAL='OPEN_SIGNUP_FORM_MODAL';
export const CLOSE_SIGNUP_FORM_MODAL='CLOSE_SIGNUP_FORM_MODAL';


// 회원가입
//
export const REQUEST_SIGNUP='REQUEST_SIGNUP';
export const RECEIVE_SIGNUP='RECEIVE_SIGNUP';


// team main
//
export const SELECT_TEAM='SELECT_TEAM';
export const REQUEST_TEAM_ID='REQUEST_TEAM_ID';
